project: ccdi-federation
services:
  backend:
    version: 2.2.0.141
    image: 2.2.0.141
    buildNumber: '141'
  frontend:
    version: 2.2.0.139
    image: 2.2.0.139
    buildNumber: '139'
  api:
    version: v1.2.5.132
    image: v1.2.5.132
    buildNumber: '132'
  dcc:
    version: cz_test.12
    image: cz_test.12
    buildNumber: '12'
