project: ccdi-federation
services:
  backend:
    version: 2.2.0.141
    image: 2.2.0.141
    buildNumber: '141'
  frontend:
    version: 2.2.0.139
    image: 2.2.0.139
    buildNumber: '139'
  api:
    version: v1.2.2.101
    image: v1.2.2.101
    buildNumber: '101'
  dcc:
    version: cz_test.7
    image: cz_test.7
    buildNumber: '7'
